---
title: "RWorksheet_Cahutay#1.Rmd"
output: pdf_document
date: "2024-09-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. A. Find the number of data points.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,
51, 35, 24, 33, 41)
length(age)
```
- There are 34 data points


2. Find Reciprocal
```{r}
reciprocal <- 1 / age
reciprocal
```

3. 
```{r}
new_age <- c(age, 0, age)
new_age
```
- It created a vector that stores the elements of age, and added zero for the element 2, and then the age vaues again stored at element 3.


4. Sort values for age.
```{r}
sort(age)
```


5. Min and Max
```{r}
min(age)
max(age)
```
- The minimum is 17 and 57 is the maximum.

6. A.
- There are 12 data points
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)
length(data)
data

```

7. Double data 
```{r}
double_data <- data * 2
data
double_data
```
- The data doubled


8. Sequence
```{r}
#8.1 - sequence from 1 - 100
sequence1 <- seq(1, 100)

#8.2 sequence from 20 - 60
sequence2 <- seq(20, 60)

#8.3 - mean of numbers from 20 - 60 is 40.
my_mean <- mean(20, 60)

#8.4 - sum of numbers from 51 - 91
sumOfNum <- sum(51:91)

#8.5 sequence from 1 - 1000
sequence3 <- seq(1, 1000)

#8.A. - data points from 8.1 - 8.4
data_pts <- c(sequence1, sequence2, my_mean, sumOfNum)
length(data_pts)
# the number of data points is 143
#below are the output
sequence1
sequence2
my_mean
sumOfNum

#8.5 - max data points until 10.
max(1, 10)
```

9. 
```{r}
filtered <- Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
filtered
```

10 - 11. 
```{r}
#10. Backward sequence
vector1 <- seq(100, 1)

# 11. filtered numbers below 25 and multiples of 3 and 5
filtered_numbers <- Filter(function(i) { (i %% 3 == 0 || i %% 5 == 0) }, seq(1:25))
filtered_numbers

#A.
data_pts2 <- c(vector1, filtered_numbers)
length(data_pts2)
# number of data points is 112
```

12.
```{r}
#x <- {0 + x + 5 + }
# there's an error saying "unexpected '}'
```

13. Vector
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75,
75, 77)
score[2]
score[3]
```

14. 
```{r}
a = c(1,2,NA,4,NA,6,7)
print(a,na.print="-999")
# the NA values of the vector 'a' was changed to -999 using the code 'a, na.print="-999"'
```

15.
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
# the output of the code above is "Input your name" and "Input your age" prompting user to input their name and age. After that, it prints all their inputted values and an added strings.
```

