---
title: "RWorksheet_Cahutay#4a"
author: "Mark Anton Cahutay"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Data Frame about shoe size and height.
```{r}
#A.  
shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender <- c('F', 'F', 'F', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'M')

shoe_data <- data.frame(
  Shoe_Size = shoe_size,
  Height = height,
  Gender = gender
)
shoe_data
#output shows the tabular data of shoe size, height, and gender.
```

```{r}
#B. Subset by males and females
males <- subset(shoe_data, Gender == "M", select = c(Shoe_Size, Height))
males

females <- subset(shoe_data, Gender == "F", select = c(Shoe_Size, Height))
females
```

```{r}
#C. Mean of the shoe size and height.
mean_shoe <- mean(shoe_data$Shoe_Size)
mean_shoe

mean_height <- mean(shoe_data$Height)
mean_height
```

```{r}
#D. Yes, there is a relationship between the shoe size and height of the respondent because when the respondent's height is taller, their shoe size is also higher.
```


2. Factor a character vector months
```{r}
months_vector <- c(
  "March", "April", "January", "November", "January", "September", 
  "October", "September", "November", "August", "January", 
  "November", "November", "February", "May", "August", "July", 
  "December", "August", "August", "September", "November", 
  "February", "April"
)
factor_months_vector <- factor(months_vector)
factor_months_vector

levels(factor_months_vector)
```


3. Check summary() of the months_vector and factor_months_vector
```{r}
summary(months_vector)
summary(factor_months_vector)

#The summary of the months_vector data shows the structure about its length, class, and mode.
#The summary of the factor_months_vector shows the frequency of the months appearing in the dataset.
#Both of the results shows relationship and useful information with each other. The summary of the months_vector provides the overall structure of the data while the results of factor_months_vector provides useful information about the content of the data.
```

4. Create vector and factor for direction table
```{r}
direction <- c("East", "West", "North")
frequency <- c(1, 4, 3)

new_order_data <- factor(direction, levels = c("East","West","North"))
print(new_order_data)
```


5. Import excel file
```{r}
#A. Import using read.table()
my_file <- read.table("import_march.csv", header = TRUE, sep = ",")

```

```{r}
#b. View the dataset. Write the R scripts and its result.
print(my_file)
``` 


6. Full Search
```{r}
#A. 
exhaustive_search <- function(user_input){
  if (user_input < 1 | user_input > 50){
    print("The number selected is beyond the range of 1 to 50")
  }else if (user_input == 20){
    print("TRUE")
  }else {
    print(user_input)
  }
}
user_input <- readline(prompt = "Select a number from 1 - 50: ")
exhaustive_search(user_input)

```


7. Change
```{r}
min_bills <- function(price){
  bills <- c(1000, 500, 200, 100, 50)
  total_bills <- 0
  
  for (bill in bills) {
    count <- floor(price / bill)
    price <- price - count * bill
    total_bills <- total_bills + count
  }
  
  return(total_bills)
}

price <- as.numeric(readline(prompt = "Enter the price of the snack: "))
print(paste("Minimum number of bills needed to purchase a snack:", min_bills(price)))
```


8. Data Frame of Student's Grade
```{r}
name <- c("Annie", "Thea", "Steve", "Hanna")
grade1 <- c(85, 65, 75, 95)
grade2 <- c(65, 75, 55, 75)
grade3 <- c(85, 90, 80, 100)
grade4 <- c(100, 90, 85, 90)

#A. data frame of student grades
student_grade <- data.frame(
  Name = name,
  Grade1 = grade1, 
  Grade2 = grade2,
  Grade3 = grade3,
  Grade4 = grade4
)
student_grade
```

```{r}
#B. Output the average score of student with an average over 90
for (i in 1:4) {
  total <- sum(student_grade[i, 2:5])  
  average <- total / 4
  
  if (average > 90){
    print(paste0(student_grade[i, 1], "'s average grade this semester is ", average))
  }
}
```

```{r}
#C. output as follows for the tests in which the average score was less than 80 out of 4 tests
for (i in 2:4){
  total <- 0
  for (j in 1:4){
    total <- total + student_grade[j, i]
  }
  
  average <- total / 4
  
  if (average < 80){
    print(paste("The", colnames(student_grade[i]), "test was difficult"))
  }
}
```

```{r}
#D. Students whose highest score for a semester exceeds 90 points.
for (j in 1:nrow(student_grade)) {  
  highest <- student_grade[j, 2]
  
  for (i in 3:ncol(student_grade)) { 
    if (student_grade[j, i] > highest) {
      highest <- student_grade[j, i]  
    }
  }
 
  if (highest >= 90){
    print(paste0(student_grade[j, 1], "'s grade this semester is ", highest))
  }
}
```




